### ISSUE TITLE
Decreasing the max-size of a node-pool doesn't terminate the nodes gracefully 

### ISSUE THREAD

**Issue by muaazsaleem** [zalando-incubator/cluster-lifecycle-manager#93]
If the node-pool size was originally 12 and was being fully used and we decrease the max-size of a node-pool i.e sth like:
```
zregistry clusters node-pools update --cluster-id <some-id> --node-pool <some-nodepool> --max-size 5
``` 
 7 of these nodes will be terminated and not gracefully. We should fix this because it might lead to poor customer experience in case of a human error. If applications running on a cluster are affected significantly enough, this might also affect end users of those applications.

**Comment by muaazsaleem** [comment]
I added the "bug" label because I believe this could do harm, feel free to change that if you disagree.

**Comment by linki** [comment]
![screen shot 2018-10-15 at 14 42 29](https://user-images.githubusercontent.com/36162/46954804-ce03f000-d091-11e8-8656-a78c3fa5e3fa.png)

**Comment by muaazsaleem** [comment]
Since creating this ticket we don't really use the `max_size` values of nodepools anymore. In most clusters it's set to be `300` (or some number we don't expect to hit). Given that there's little value from implementing this (and a lot of effort) I'm closing this.

Feel free to re-open in case of comments/questions.
