### ISSUE TITLE
CLM doesn't respect current size when setting max size

### ISSUE THREAD

**Issue by linki** [zalando-incubator/cluster-lifecycle-manager#95]
When the value of `max` nodes of a node pool is lower than the `current` CLM should refrain from setting it.

But today, it did.

**Comment by mikkeloscar** [comment]
This is the same issue as described in #93 right?

**Comment by linki** [comment]
![screen shot 2018-10-15 at 14 42 29](https://user-images.githubusercontent.com/36162/46951635-da377f80-d088-11e8-8694-ef92ec762b8f.png)

**Comment by linki** [comment]
could be, I'll check and merge them later.

**Comment by linki** [comment]
Looks the same to me. Closing.
